"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read configuration from a local .env file, if present.
# Real environment variables take precedence over .env values.
load_dotenv(BASE_DIR / ".env")


def _env_bool(name: str, default: str) -> bool:
    """Parse a boolean env var robustly ('true'/'1'/'yes'/'on' -> True)."""
    return os.environ.get(name, default).strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to true so fresh dev clones work; set DJANGO_DEBUG=false in prod.
DEBUG = _env_bool("DJANGO_DEBUG", default="true")

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in .env; generate one with e.g.
#   python -c "import secrets; print(secrets.token_urlsafe(50))"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        # DEV ONLY: ephemeral key so fresh clones can run tests without a
        # .env. Regenerated on every process start — sessions/signatures do
        # not survive restarts. Never used when DEBUG is false.
        from django.core.management.utils import get_random_secret_key

        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false. "
            "Generate one with: python -c \"from django.core.management.utils "
            "import get_random_secret_key; print(get_random_secret_key())\""
        )

# Comma-separated hostnames, e.g. "example.com,www.example.com".
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1"
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    # django.contrib.admin deliberately not installed: no models are
    # registered, so its login page would be pure attack surface.
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "practice",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where collectstatic gathers files for production serving (gitignored).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Per-IP request cap for POST /api/log/, enforced by practice/ratelimit.py
# over a fixed one-minute window. Set to 0 (or negative) to disable.
API_RATE_LIMIT_PER_MINUTE = int(
    os.environ.get("DJANGO_API_RATE_LIMIT_PER_MINUTE", "60")
)


# Production hardening — applied whenever DEBUG is off.
# If the app sits behind a TLS-terminating reverse proxy, also set
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") and ensure the
# proxy strips any client-supplied X-Forwarded-Proto header.

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Start with a short HSTS max-age; raise to 31536000 (1 year) once HTTPS
    # is confirmed stable, then consider enabling preload.
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", default="false")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
