# Generated by Django 5.2.16 on 2026-07-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_id", models.CharField(max_length=64)),
                ("scale", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=3)),
                ("direction", models.CharField(max_length=16)),
                ("correct", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
