# Generated by Django 5.2.16 on 2026-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptlog",
            name="is_retry",
            field=models.BooleanField(default=False),
        ),
    ]
