# Generated by Django 5.2.16 on 2026-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_attemptlog_is_retry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptlog",
            name="direction",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
